// SPDX-License-Identifier: MIT
// Copyright (c) 2024 PlebOne

import { describe, expect, it } from 'vitest'
import { parseSrcInfo } from './srcinfo'

const SAMPLE = `# Generated by makepkg
pkgbase = foo
pkgname = foo
pkgver = 1.2.3
pkgdesc = A test package
arch = amd64
arch = arm64
maintainer = Jane Doe <jane@example.com>
url = https://example.com/foo
license = MIT
depends = libc6
depends = libssl3
optdepends = python: for scripting
makedepends = make
source = https://example.com/foo.tar.gz
source_amd64 = https://example.com/foo-amd64.tar.gz
sha256sums = abc
sha256sums_amd64 = def

# trailing comment
`

describe('parseSrcInfo — scalars and arrays', () => {
  it('parses scalar fields', () => {
    const info = parseSrcInfo(SAMPLE)
    expect(info.pkgname).toBe('foo')
    expect(info.pkgver).toBe('1.2.3')
    expect(info.pkgdesc).toBe('A test package')
    expect(info.maintainer).toBe('Jane Doe <jane@example.com>')
    expect(info.url).toBe('https://example.com/foo')
  })

  it('accumulates repeated keys into arrays', () => {
    const info = parseSrcInfo(SAMPLE)
    expect(info.arch).toEqual(['amd64', 'arm64'])
    expect(info.depends).toEqual(['libc6', 'libssl3'])
    expect(info.optdepends).toEqual(['python: for scripting'])
    expect(info.makedepends).toEqual(['make'])
    expect(info.license).toEqual(['MIT'])
  })

  it('merges arch-specific keys into their base array in order', () => {
    const info = parseSrcInfo(SAMPLE)
    expect(info.source).toEqual([
      'https://example.com/foo.tar.gz',
      'https://example.com/foo-amd64.tar.gz'
    ])
    expect(info.sha256sums).toEqual(['abc', 'def'])
  })

  it('ignores comments and blank lines', () => {
    const info = parseSrcInfo('# comment\n\npkgname = foo\n# another\n')
    expect(info.pkgname).toBe('foo')
  })
})

describe('parseSrcInfo — pkgbase / pkgname', () => {
  it('falls back to pkgbase when there is no pkgname', () => {
    expect(parseSrcInfo('pkgbase = foo\npkgver = 1.0\n').pkgname).toBe('foo')
  })

  it('prefers pkgname over pkgbase', () => {
    expect(parseSrcInfo('pkgbase = base\npkgname = foo\n').pkgname).toBe('foo')
  })

  it('takes the first pkgname of a split package', () => {
    expect(parseSrcInfo('pkgname = foo\npkgname = bar\n').pkgname).toBe('foo')
  })
})

describe('parseSrcInfo — malformed input never throws', () => {
  it('returns empty defaults for empty or junk input', () => {
    for (const input of ['', '   ', 'not a srcinfo', '= = =', 'no equals sign here']) {
      const info = parseSrcInfo(input)
      expect(info.pkgname).toBe('')
      expect(info.pkgver).toBe('')
      expect(info.depends).toEqual([])
      expect(info.source).toEqual([])
    }
  })

  it('keeps lines without an equals sign from aborting the parse', () => {
    const info = parseSrcInfo('garbage\npkgname = foo\nmore garbage\npkgver = 2.0')
    expect(info.pkgname).toBe('foo')
    expect(info.pkgver).toBe('2.0')
  })

  it('trims surrounding whitespace from keys and values', () => {
    expect(parseSrcInfo('  pkgname   =   foo  \n').pkgname).toBe('foo')
  })
})
